// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PureFin.Backend.Data;

#nullable disable

namespace PureFin.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260117203738_AddAuthAndSimulationUpdates")]
    partial class AddAuthAndSimulationUpdates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PureFin.Backend.Features.Auth.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PureFin.Backend.Features.Simulation.Data.SimulationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CalculatedCorpTax")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CalculatedIPP")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CalculatedNetAnnual")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CalculatedReserves")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CalculatedSocialContributions")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CarMonthly")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GrossSalaryMonthly")
                        .HasColumnType("numeric");

                    b.Property<decimal>("InsuranceAnnual")
                        .HasColumnType("numeric");

                    b.Property<decimal>("InternetMonthly")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MealVouchersMonthly")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("OtherAnnual")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PensionAnnual")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PhoneMonthly")
                        .HasColumnType("numeric");

                    b.Property<decimal>("RestaurantMonthly")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Simulations");
                });

            modelBuilder.Entity("PureFin.Backend.Features.Simulation.Data.SimulationEntity", b =>
                {
                    b.HasOne("PureFin.Backend.Features.Auth.Models.User", "User")
                        .WithMany("Simulations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("PureFin.Backend.Features.Auth.Models.User", b =>
                {
                    b.Navigation("Simulations");
                });
#pragma warning restore 612, 618
        }
    }
}
