// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PureFin.Backend.Data;

#nullable disable

namespace PureFin.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260114214304_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PureFin.Backend.Features.Simulation.Data.SimulationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CalculatedCompanyTax")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CalculatedNetSalary")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GrossSalary")
                        .HasColumnType("numeric");

                    b.Property<bool>("IncludeAccountant")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludeCar")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludeInsurance")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludeInternet")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludeMealVouchers")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Simulations");
                });
#pragma warning restore 612, 618
        }
    }
}
